#############################################################################
# Makefile for building: TA3.app/Contents/MacOS/TA3
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ??? 5 13:30:09 2017
# Project:  TA3.pro
# Template: app
# Command: /Developer/qt/bin/qmake -o Makefile TA3.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -std=c++11 -stdlib=libc++ -pipe -O3 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
CXXFLAGS      = -std=c++11 -stdlib=libc++ -pipe -O3 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
INCPATH       = -I/Developer/qt/mkspecs/macx-g++ -I. -I/Developer/qt/include/QtCore -I/Developer/qt/include/QtGui -I/Developer/qt/include -I. -Isrc -I.
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -all_load -Xarch_x86_64 -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS)  -L/Developer/qt/lib -lQtGui -L/Developer/qt/lib -framework ApplicationServices -framework CoreFoundation -framework Security -framework Carbon -framework AppKit -lQtCore -lz -lm -lc++
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         =
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/aligner.cpp \
		src/main.cpp qrc_ta3res.cpp
OBJECTS       = aligner.o \
		main.o \
		qrc_ta3res.o
DIST          = /Developer/qt/mkspecs/common/unix.conf \
		/Developer/qt/mkspecs/common/mac.conf \
		/Developer/qt/mkspecs/common/gcc-base.conf \
		/Developer/qt/mkspecs/common/gcc-base-macx.conf \
		/Developer/qt/mkspecs/common/g++-base.conf \
		/Developer/qt/mkspecs/common/g++-macx.conf \
		/Developer/qt/mkspecs/qconfig.pri \
		/Developer/qt/mkspecs/features/qt_functions.prf \
		/Developer/qt/mkspecs/features/qt_config.prf \
		/Developer/qt/mkspecs/features/exclusive_builds.prf \
		/Developer/qt/mkspecs/features/default_pre.prf \
		/Developer/qt/mkspecs/features/mac/default_pre.prf \
		/Developer/qt/mkspecs/features/release.prf \
		/Developer/qt/mkspecs/features/default_post.prf \
		/Developer/qt/mkspecs/features/mac/default_post.prf \
		/Developer/qt/mkspecs/features/mac/x86_64.prf \
		/Developer/qt/mkspecs/features/mac/objective_c.prf \
		/Developer/qt/mkspecs/features/static.prf \
		/Developer/qt/mkspecs/features/warn_on.prf \
		/Developer/qt/mkspecs/features/qt.prf \
		/Developer/qt/mkspecs/features/unix/thread.prf \
		/Developer/qt/mkspecs/features/moc.prf \
		/Developer/qt/mkspecs/features/mac/rez.prf \
		/Developer/qt/mkspecs/features/mac/sdk.prf \
		/Developer/qt/mkspecs/features/resources.prf \
		/Developer/qt/mkspecs/features/uic.prf \
		/Developer/qt/mkspecs/features/yacc.prf \
		/Developer/qt/mkspecs/features/lex.prf \
		/Developer/qt/mkspecs/features/include_source_dir.prf \
		TA3.pro
QMAKE_TARGET  = TA3
DESTDIR       =
TARGET        = TA3.app/Contents/MacOS/TA3

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile TA3.app/Contents/PkgInfo TA3.app/Contents/Resources/empty.lproj TA3.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)
	@$(CHK_DIR_EXISTS) TA3.app/Contents/MacOS/ || $(MKDIR) TA3.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TA3.pro  /Developer/qt/mkspecs/macx-g++/qmake.conf /Developer/qt/mkspecs/common/unix.conf \
		/Developer/qt/mkspecs/common/mac.conf \
		/Developer/qt/mkspecs/common/gcc-base.conf \
		/Developer/qt/mkspecs/common/gcc-base-macx.conf \
		/Developer/qt/mkspecs/common/g++-base.conf \
		/Developer/qt/mkspecs/common/g++-macx.conf \
		/Developer/qt/mkspecs/qconfig.pri \
		/Developer/qt/mkspecs/features/qt_functions.prf \
		/Developer/qt/mkspecs/features/qt_config.prf \
		/Developer/qt/mkspecs/features/exclusive_builds.prf \
		/Developer/qt/mkspecs/features/default_pre.prf \
		/Developer/qt/mkspecs/features/mac/default_pre.prf \
		/Developer/qt/mkspecs/features/release.prf \
		/Developer/qt/mkspecs/features/default_post.prf \
		/Developer/qt/mkspecs/features/mac/default_post.prf \
		/Developer/qt/mkspecs/features/mac/x86_64.prf \
		/Developer/qt/mkspecs/features/mac/objective_c.prf \
		/Developer/qt/mkspecs/features/static.prf \
		/Developer/qt/mkspecs/features/warn_on.prf \
		/Developer/qt/mkspecs/features/qt.prf \
		/Developer/qt/mkspecs/features/unix/thread.prf \
		/Developer/qt/mkspecs/features/moc.prf \
		/Developer/qt/mkspecs/features/mac/rez.prf \
		/Developer/qt/mkspecs/features/mac/sdk.prf \
		/Developer/qt/mkspecs/features/resources.prf \
		/Developer/qt/mkspecs/features/uic.prf \
		/Developer/qt/mkspecs/features/yacc.prf \
		/Developer/qt/mkspecs/features/lex.prf \
		/Developer/qt/mkspecs/features/include_source_dir.prf \
		/Developer/qt/lib/libQtGui.prl \
		/Developer/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile TA3.pro
/Developer/qt/mkspecs/common/unix.conf:
/Developer/qt/mkspecs/common/mac.conf:
/Developer/qt/mkspecs/common/gcc-base.conf:
/Developer/qt/mkspecs/common/gcc-base-macx.conf:
/Developer/qt/mkspecs/common/g++-base.conf:
/Developer/qt/mkspecs/common/g++-macx.conf:
/Developer/qt/mkspecs/qconfig.pri:
/Developer/qt/mkspecs/features/qt_functions.prf:
/Developer/qt/mkspecs/features/qt_config.prf:
/Developer/qt/mkspecs/features/exclusive_builds.prf:
/Developer/qt/mkspecs/features/default_pre.prf:
/Developer/qt/mkspecs/features/mac/default_pre.prf:
/Developer/qt/mkspecs/features/release.prf:
/Developer/qt/mkspecs/features/default_post.prf:
/Developer/qt/mkspecs/features/mac/default_post.prf:
/Developer/qt/mkspecs/features/mac/x86_64.prf:
/Developer/qt/mkspecs/features/mac/objective_c.prf:
/Developer/qt/mkspecs/features/static.prf:
/Developer/qt/mkspecs/features/warn_on.prf:
/Developer/qt/mkspecs/features/qt.prf:
/Developer/qt/mkspecs/features/unix/thread.prf:
/Developer/qt/mkspecs/features/moc.prf:
/Developer/qt/mkspecs/features/mac/rez.prf:
/Developer/qt/mkspecs/features/mac/sdk.prf:
/Developer/qt/mkspecs/features/resources.prf:
/Developer/qt/mkspecs/features/uic.prf:
/Developer/qt/mkspecs/features/yacc.prf:
/Developer/qt/mkspecs/features/lex.prf:
/Developer/qt/mkspecs/features/include_source_dir.prf:
/Developer/qt/lib/libQtGui.prl:
/Developer/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TA3.pro

TA3.app/Contents/PkgInfo:
	@$(CHK_DIR_EXISTS) TA3.app/Contents || $(MKDIR) TA3.app/Contents
	@$(DEL_FILE) TA3.app/Contents/PkgInfo
	@echo "APPL????" >TA3.app/Contents/PkgInfo
TA3.app/Contents/Resources/empty.lproj:
	@$(CHK_DIR_EXISTS) TA3.app/Contents/Resources || $(MKDIR) TA3.app/Contents/Resources
	@touch TA3.app/Contents/Resources/empty.lproj

TA3.app/Contents/Info.plist:
	@$(CHK_DIR_EXISTS) TA3.app/Contents || $(MKDIR) TA3.app/Contents
	@$(DEL_FILE) TA3.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,TA3,g" -e "s,@TYPEINFO@,????,g" /Developer/qt/mkspecs/macx-g++/Info.plist.app >TA3.app/Contents/Info.plist
dist:
	@$(CHK_DIR_EXISTS) .tmp/TA31.0.0 || $(MKDIR) .tmp/TA31.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TA31.0.0/ && $(COPY_FILE) --parents src/align_writer.h src/aligner.h src/dna_util.h src/dotmatrix_drawer.h src/fastq_reader.h src/frames_drawer.h src/indexref.h src/option_parser.h src/orf_finder.h src/tless.h .tmp/TA31.0.0/ && $(COPY_FILE) --parents res/ta3res.qrc .tmp/TA31.0.0/ && $(COPY_FILE) --parents src/aligner.cpp src/main.cpp .tmp/TA31.0.0/ && (cd `dirname .tmp/TA31.0.0` && $(TAR) TA31.0.0.tar TA31.0.0 && $(COMPRESS) TA31.0.0.tar) && $(MOVE) `dirname .tmp/TA31.0.0`/TA31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TA31.0.0


clean:compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r TA3.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all: qrc_ta3res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ta3res.cpp
qrc_ta3res.cpp: res/ta3res.qrc \
		res/logo.png
	/Developer/qt/bin/rcc -name ta3res res/ta3res.qrc -o qrc_ta3res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean

####### Compile

aligner.o: src/aligner.cpp src/aligner.h \
		src/indexref.h \
		src/tless.h \
		src/dna_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aligner.o src/aligner.cpp

main.o: src/main.cpp src/dna_util.h \
		src/tless.h \
		src/indexref.h \
		src/fastq_reader.h \
		src/aligner.h \
		src/option_parser.h \
		src/align_writer.h \
		src/dotmatrix_drawer.h \
		src/orf_finder.h \
		src/frames_drawer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qrc_ta3res.o: qrc_ta3res.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ta3res.o qrc_ta3res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:
